import { QUERY_COMPANY_INFO, QUERY_DRAGONS, QUERY_DRAGON_ID } from "./ganarel";
import { QUERY_USERS_INFO, MUTATE_INSERT_USERS } from "./users";

export {
  QUERY_COMPANY_INFO,
  QUERY_DRAGONS,
  QUERY_DRAGON_ID,
  QUERY_USERS_INFO,
  MUTATE_INSERT_USERS,
};
